# Rede Neural Keras

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

2023-05-03 15:01:04.258010: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-03 15:01:04.814064: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-03 15:01:04.816252: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-03 15:01:07.317543: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [5]:
# Carregando a base de dados e criando os previsores (Variaveis independentes X) e classe (variaveis dependentes Y)
base = datasets.load_iris()
previsores = base.data # Array com as quatro colunas do arquivo
classe = base.target # Transforma valor categorico em valor numerico
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
# Transformação da classe para o formato dummy, pois temos uma rede neural de 3 neuronios na camada de saida
classe_dummy = np_utils.to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [8]:
X_train, X_test, y_train, y_test = train_test_split(previsores, classe_dummy, test_size=0.3, random_state=0)

In [11]:
# Criação da primeira estrutura da rede neural com a classe Sequential (sequencia de camadas)
modelo = Sequential() # Camadas sequencial
# primeira camada oculta 
# 5 neuronios, 4 neuronios de entrada
# Camada do tipo Dense significa que são todas conectadas
# imput_dim a respeito das 4 colunas do arquivo
modelo.add(Dense(units=5, input_dim=4)) 
# Segunda camada oculta
modelo.add(Dense(units=4))

# Terceira camada oculta
# Função de ativação = softmax
# Função softmax porque temos um problema de classificação com mais de duas classes (é gerada uma probabilidade em cada neuronio)
modelo.add(Dense(units=3, activation='softmax'))

In [10]:
# Visualização da estrutura da rede neural
modelo.summary()

In [12]:
# Configuração dos parametros da rede neural (adam - algoritmo para atualizar os pesos, loss o calculo do erro)
# optmizer > otimiza os pesos, loss > função de perda, metrics > para medir o erro
modelo.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])

# Treinamento, dividindo a base de treinamento em uma porção para validação (validation_data)
modelo.fit(X_train, y_train, epochs=1000, validation_data=(X_test, y_test))

Epoch 1/1000
4/4 [==============================] - 1s 92ms/step - loss: 2.7668 - accuracy: 0.3048 - val_loss: 2.3810 - val_accuracy: 0.4000
Epoch 2/1000
4/4 [==============================] - 0s 15ms/step - loss: 2.5069 - accuracy: 0.3048 - val_loss: 2.1843 - val_accuracy: 0.4000
Epoch 3/1000
4/4 [==============================] - 0s 17ms/step - loss: 2.2685 - accuracy: 0.3048 - val_loss: 2.0067 - val_accuracy: 0.4000
Epoch 4/1000
4/4 [==============================] - 0s 20ms/step - loss: 2.0517 - accuracy: 0.3048 - val_loss: 1.8557 - val_accuracy: 0.4000
Epoch 5/1000
4/4 [==============================] - 0s 24ms/step - loss: 1.8527 - accuracy: 0.3048 - val_loss: 1.7350 - val_accuracy: 0.4000
Epoch 6/1000
4/4 [==============================] - 0s 20ms/step - loss: 1.7066 - accuracy: 0.3048 - val_loss: 1.6452 - val_accuracy: 0.3778
Epoch 7/1000
4/4 [==============================] - 0s 33ms/step - loss: 1.5945 - accuracy: 0.2952 - val_loss: 1.5876 - val_accuracy: 0.3778
Epoch 8/1000


In [35]:
# Previsoes e mudar a variavel para true ou false de acordo com threshold
previsoes = modelo.predict(X_test)
previsoes = (previsoes > 0.5)
len(previsoes)

2/2 [==============================] - 0s 5ms/step


45

In [37]:
# Como é um problema com três saidas, precisamos buscar a posição que possui o maior valor (são retornados 3 valores)
y_test_matrix = [np.argmax(t) for t in y_test]
y_previsao_matrix = [np.argmax(g) for g in previsoes]


In [38]:
# Geração da matriz de confusão
confusao = confusion_matrix(y_test_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])